// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE3HkF2B_iQ59wfUE3VUnrDwbcn86B__k',
    appId: '1:505753306612:web:2a33724be78572e7db25a1',
    messagingSenderId: '505753306612',
    projectId: 'firstproj-eedf9',
    authDomain: 'firstproj-eedf9.firebaseapp.com',
    storageBucket: 'firstproj-eedf9.appspot.com',
    measurementId: 'G-CLWHKL5LZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm1-mz4C-kKd1s09z5FEGQYlXd4uh7vmg',
    appId: '1:505753306612:android:471505be6eba8f01db25a1',
    messagingSenderId: '505753306612',
    projectId: 'firstproj-eedf9',
    storageBucket: 'firstproj-eedf9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhMlrOD8C3yo7l3Slx8a9kX3Gi4uJhgRg',
    appId: '1:505753306612:ios:a51938406e29f7addb25a1',
    messagingSenderId: '505753306612',
    projectId: 'firstproj-eedf9',
    storageBucket: 'firstproj-eedf9.appspot.com',
    iosClientId: '505753306612-48k5vs8fqqu50i0aub5n4u2hosvsa4hf.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalApp',
  );
}
